### PR TITLE
(LEARNVM-476) Corrected whitespace

### PR DESCRIPTION
**Pull request by kavixiu**
Removed whitespace from code examples to maintain consistency throughout questguide

### CODE REVIEW

**Comment by kjhenner** [comment]
@kavixiu Could you please reset the ja_jp versions of these files? Those will be updated based on changes to the English version through the Tranisfex integration. Apologies for not letting you know about that before you did the work!

**Comment by greglarkin** [comment]
Should I merge this PR @kjhenner, or did you mean you want the additional ja_jp work to be added to this one?

**Comment by kavixiu** [comment]
No problem -- I reverted the whitespace changes to the ja_jp files so they should be good to go now.

**Comment by kavixiu** [comment]
@kjhenner

**Pull request merged**
